#!/bin/sh
# $HOME/etc/profile
# source our shellrc
case $SHELL in
    *mksh*) . $HOME/etc/mkshrc;;
    *bash*) . $HOME/etc/bashrc;;
esac

# exporting variables
export TERMINAL="tabbed -c -r 2 st -w ''"

# path variables
export PATH=$PATH:$HOME/bin:$HOME/.local/bin:$HOME/usr/local
export PATH=$PATH:$HOME/usr/local/bin

# XDG env vars
export XDG_CACHE_HOME="$HOME/var/cache"
export XDG_CONFIG_HOME="$HOME/etc"
export XDG_DESKTOP_DIR="/non/existent"
export XDG_DOWNLOAD_DIR="$HOME/var/downloads"

# mail vars
export MAIL="$HOME/var/mail/inbox"

# Xorg
export XAUTHORITY="$XDG_CACHE_HOME/Xauthority"
